package com.sebasira.MediumTutorialSecurity.model;

import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;

/**
 * Created by sebas on 17/07/17.
 */
@Entity                     // Entity clas
@Table(name = "client")     // Table user
public class Client {

    /* ID */
    /* ** */
    /**
     * This is the ID field, AUTOGENERATED. It's the client_id column inside the table
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "client_id")
    private long id;
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    /* NAME */
    /* **** */
    @Column(name = "name")
    @NotEmpty(message = "*Please provide a name for the client")
    private String name;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }


    /* LAST NAME */
    /* ********* */
    @Column(name = "last_name")
    @NotEmpty(message = "*Please provide a last name for the client")
    private String lastName;
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    /* STATE */
    /* ***** */
    @Column(name = "state")
    private int state;
    public int getState() {
        return state;
    }
    public void setState(int state) {
        this.state = state;
    }


    /* USER */
    /* **** */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User userOwner;
    public User getUser() {
        return userOwner;
    }
    public void setUser(User user) {
        this.userOwner = user;
    }
}
