package com.sebasira.MediumTutorialSecurity.model;

/**
 * Created by sebas on 16/07/17.
 */


import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import java.util.Set;

/**
 * Using Annotations
 *
 * This is an Entity Class for modeling USER, also use Hibernate Annotations
 * to define table name it belongs to
 */
@Entity                     // Entity clas
@Table(name = "user")       // Table user
public class User {

    /* ID */
    /* ** */
    /**
     * This is the ID field, AUTOGENERATED. It's the user_id column inside the table
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "user_id")
    private int id;
    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }


    /* E-MAIL */
    /* ****** */
    /**
     * Uses Hibernate annotations for validation
     */
    @Column(name = "email")
    @Email(message = "*Please provide a valid Email")
    @NotEmpty(message = "*Please provide an email")
    private String email;
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }


    /* PASSWORD */
    /* ******** */
    @Column(name = "password")
    @Length(min = 5, message = "*Your password must have at least 5 characters")
    @NotEmpty(message = "*Please provide your password")
    @Transient
    private String password;
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }


    /* NAME */
    /* **** */
    @Column(name = "name")
    @NotEmpty(message = "*Please provide your name")
    private String name;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }


    /* LAST NAME */
    /* ********* */
    @Column(name = "last_name")
    @NotEmpty(message = "*Please provide your last name")
    private String lastName;
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    /* ACTIVE */
    /* ****** */
    @Column(name = "active")
    private int active;
    public int getActive() {
        return active;
    }
    public void setActive(int active) {
        this.active = active;
    }


    /* ROLES */
    /* ***** */
    @ManyToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> roles;
    public Set<Role> getRoles() {
        return roles;
    }
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
}
